tooltip`s added
js-tasks-ru/htmlcss-20240913_radionova-elena pull request #11
Opened 2024-10-02 12:21 UTC by ElenaVlasenko

2024-10-02 12:22 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-04 20:21 UTC, GSemikozov requested changes

2024-10-04 20:21 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: 60px;
марджины на уровне блока не задаем

2024-10-14 04:31 UTC, GSemikozov requested changes

2024-10-14 04:31 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.wrapper {
здесь описываем блок .tooltip, а .wrapper - по семантике и смыслу совершенно другой блок :) вспомогательные обертки при решении задач можно создавать, но в отдельных файлах

2024-11-12 08:21 UTC, GSemikozov requested changes

2024-11-12 08:21 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    left: 60px;
лишнее

2024-11-12 08:21 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top: 60px;
лишнее

2025-02-20 20:13 UTC, GSemikozov approved these changes

2025-02-20 20:13 UTC, merged