Lection4 svg sprite
js-tasks-ru/htmlcss-20240913_radionova-elena pull request #19
Opened 2024-10-12 13:02 UTC by ElenaVlasenko

2024-10-12 13:02 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-12 13:07 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-12 13:44 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-21 14:11 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-21 22:17 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-22 22:57 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-27 14:10 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-27 14:15 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-27 14:20 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-12 08:28 UTC, GSemikozov requested changes

2024-11-12 08:28 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.wrapper {
удалим (нужно актуализировать после того как смерджим тултип)

2024-11-12 08:28 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modalBackdrop {
и модалку

2025-02-20 20:17 UTC, GSemikozov approved these changes

2025-02-20 20:17 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2025-02-20 20:17 UTC, GSemikozov requested changes
нужно поправить конфликт

2025-03-09 18:47 UTC, GSemikozov approved these changes

2025-03-09 18:47 UTC, merged