Lection5 radio
js-tasks-ru/htmlcss-20240913_radionova-elena pull request #21
Opened 2024-10-31 22:49 UTC by ElenaVlasenko

2024-10-31 22:50 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-12 08:30 UTC, GSemikozov requested changes

2024-11-12 08:30 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +     display: none;
иконку (кружок) можно отрисовать просто через css :)

2024-11-12 08:30 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> + .radio-wrapper {
см комменты в ПР-е по чекбоксу

2024-12-01 14:24 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2025-01-05 22:04 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2025-01-05 22:36 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2025-01-06 15:31 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2025-01-07 08:17 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2025-01-07 08:24 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2025-02-20 20:19 UTC, GSemikozov requested changes

2025-02-20 20:19 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +     display: flex;
30-32 - лишние строки

2025-02-20 20:19 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +     display: none;
можно скрывать / показывать через opacity

2025-02-20 20:19 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> + .radio-wrapper {
надо удалить

2025-03-09 18:47 UTC, GSemikozov approved these changes

2025-03-09 18:48 UTC, merged