histogram`s realized
js-tasks-ru/htmlcss-20240913_radionova-elena pull request #8
Opened 2024-09-29 12:39 UTC by ElenaVlasenko

2024-09-29 12:40 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-29 18:32 UTC, GSemikozov requested changes

2024-09-29 18:32 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 16px 24px;
`16 24 24`

2024-09-29 18:32 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.block {
.histogram__block?

2024-09-29 18:32 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.block_large {
.histogram__block_large и тд

2024-09-29 18:32 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    gap: 1px;
здеь же еще фиксируем высоту 50px

2024-09-29 18:32 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 50px;
точно речь о ширине?)

на самом деле достаточно flex-grow: 1

2024-09-29 18:32 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 100px;
высоту - в процентах

2024-09-29 18:32 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.content__number {
.histogram__number?

2024-09-29 18:32 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.content__link {
.histogram__link

2024-09-29 18:32 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    color: var(--histogram);
еще вроде паддинг или марджин сверху 3px

2024-09-29 18:32 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +p {
глобальные сбросы? тогда в normalize

2024-09-29 18:32 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <p class="content__link">View all</p>
`<a>`

2024-09-30 09:12 UTC, ElenaVlasenko commented on 04-lection2/01-histogram/histogram.css
> +    gap: 1px;
50% может? с 50px выглядит странно

2024-09-30 17:19 UTC, ElenaVlasenko commented on 04-lection2/01-histogram/histogram.css
> +p {
не поняла. я просто цвет не нашла в main.css и добавила в root свой. так нельзя делать? или нужно прямо правило  в normalize добавить?  если в normalize, то как? .histogram__link { --histogram: #4263EB;} ??

2024-10-02 09:40 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    gap: 1px;
в макете 50px

2024-10-02 09:42 UTC, GSemikozov requested changes

2024-10-02 09:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 100px;
все еще актуально. Высота колонок должна быть от 1 до 100, такие значения нам будет отдавать сервер, значит - работает в процентах относительно высоты родителя

2024-10-02 09:42 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +p {
здесь вопрос про вот это:
```
p {
    margin: 0;
}
```
это же глобальные сбросы, их нельзя описывать в файлах компонентов)

2024-10-14 04:25 UTC, GSemikozov approved these changes

2024-10-14 04:25 UTC, merged