skeleton`s realized
js-tasks-ru/htmlcss-20240913_radionova-elena pull request #9
Opened 2024-09-29 14:47 UTC by ElenaVlasenko

2024-09-29 14:47 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-29 18:34 UTC, GSemikozov requested changes

2024-09-29 18:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    gap: 32px;
24

2024-09-29 18:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_header {
элементы же пишем через `__` :)

2024-09-29 18:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding-top: 8px;
кажется лишним

2024-09-29 18:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.line {
.skeleton__line?

2024-09-29 18:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.line__short {
.skeleton__line_short

2024-09-29 18:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
в процентах

2024-09-29 18:34 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.header_avatar {
.skeleton__avatar?

2024-09-29 23:04 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-29 23:14 UTC, ElenaVlasenko commented on 04-lection2/02-skeleton/skeleton.css
> +    padding-top: 8px;
а там ведь до кружка меньше, чем до текста. Если убрать 8, то аватарка и текст окажутся на одной линии..

2024-09-29 23:16 UTC, ElenaVlasenko commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_header {
не знаю как так вышло :0

2024-09-29 23:35 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-09-30 07:01 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-10-02 09:39 UTC, GSemikozov requested changes

2024-10-02 09:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding-top: 8px;
да, но при этом их высота будет одинаковой) что есть title-lines задать align-items: center?

2024-10-04 20:15 UTC, GSemikozov approved these changes

2024-10-04 20:15 UTC, merged